# Generated by Django 3.2.6 on 2021-08-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('publicado', 'Publicado'), ('banido', 'Banido')], default='publicado', max_length=10),
        ),
    ]
