// PROMOTION ACTIONS
export const PROMOTION_LIST_REQUEST = 'PROMOTION_LIST_REQUEST';
export const PROMOTION_LIST_SUCCESS = 'PROMOTION_LIST_SUCCESS';
export const OWN_PROMOTION_LIST_REQUEST = 'OWN_PROMOTION_LIST_REQUEST';
export const OWN_PROMOTION_LIST_SUCCESS = 'OWN_PROMOTION_LIST_SUCCESS';
export const PROMOTION_CREATE_REQUEST = 'PROMOTION_CREATE_REQUEST';
export const PROMOTION_CREATE_SUCCESS = 'PROMOTION_CREATE_SUCCESS';

export const CATEGORIES_LIST_SUCCESS = 'CATEGORIES_LIST_SUCCESS';
//USER ACTIONS
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';